version: '3.1'

services:
  nginx:
    build: 'nginx'
    container_name: 'nginx'
    ports:
      - 80:80
      - 9001:9001
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/supervisord.conf:/etc/supervisord.conf
      # - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  express:
    build: ./
    container_name: 'express'
    tty: true
    environment:
      - NODE_ENV=production
      - MONGO_DATABASE=mongodb://mongo
      # - REDIS_HOST=127.0.0.1
    ports:
      - 3000:3000
    links:
      - mongo
      - redis
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app

  mongo:
    image: mongo:latest
    container_name: 'mongo'
    # command:
    #   - mongod
    restart: always
    environment:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example01
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - 27017:27017
    # volumes:
    #   - ./db:/data/db
    #   - ./configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example01

  redis:
    image: redis
    container_name: 'redis'
    ports:
      - 6379:6379

  redis-slave:
    image: redis
    container_name: 'redis-slave'
    ports:
      - 6479:6379
    links:
      - redis
    command: redis-server --slaveof redis 6379
    # command: redis-server --slaveof 0.0.0.0 6379
